version: "3.9"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gatsby-starter
    ports:
      - "8000:8000"
    volumes:
      - .:/home/node/app
    environment:
      - NODE_ENV=development
    tty: true
    stdin_open: true
